### ISSUE TITLE
WatchFragments Request

### ISSUE THREAD

**Issue by rmnvncnt** [philbot9/youtube-comments-task#2]
Not an actual problem with the code, but a question regarding the way it works. As I understand, you send a POST request to the `watch_fragments_ajax` server with : 
- This query string : {
    'v' : video_id,
    'tr' : 'time',
    'distiller' : '1',
    'ctoken' : comment_token,
    'frags' : 'comments',
    'spf' : 'load'
}
- This data : {
    "session_token" : session_token,
    "client_url" : client_url,
}
- This header : {
    'Accept-Language' : 'en-US;q=0.9,en;',
}

But when I try to send the same request with my own script, I get 403'd. Is there something I'm missing?

**Comment by philbot9** [comment]
Hi there,

Off the top of my head... Did you include the cookies you received on the previous requests? 

Other than that, I can't really tell without looking at some code. Can you post the relevant parts?

**Comment by rmnvncnt** [comment]
Yep, that was the issue! Thanks for the input!

**Comment by philbot9** [comment]
No problem.
